name: Compilar LineageOS para Vili

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Limpiar espacio en disco
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          echo "Espacio liberado manualmente."

      - name: Configurar entorno de Android
        run: |
          sudo apt-get update || true
          sudo apt-get install -y --fix-missing bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32z1-dev libelf-dev libgl1-mesa-dev libxml2-utils xsltproc zip zlib1g-dev

      - name: Instalar Repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          git config --global user.name "owens-android"
          git config --global user.email "jlorito8@gmail.com"

      - name: Sincronizar fuentes de LineageOS y Vili
        run: |
          mkdir android-workspace && cd android-workspace
          ~/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs
          git clone https://github.com/TU_USUARIO/local_manifests .repo/local_manifests
          ~/bin/repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Compilar ROM
        run: |
          cd android-workspace
          source build/envsetup.sh
          lunch lineage_vili-userdebug
          mka bacon -j$(nproc --all)

      - name: Guardar la ROM compilada
        uses: actions/upload-artifact@v4
        with:
          name: LineageOS-Vili-Zip
          path: android-workspace/out/target/product/vili/*.zip
